const SEATS = [
    {
      id: 'A-36',
      row: 'A',
      column: 36,
      code: '43676767663',
      selection: false,
      color: 'grey',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1403.1,
      cy: 335.6
    },
    {
      id: 'A-37',
      row: 'A',
      column: 37,
      code: '97788777568',
      selection: false,
      color: 'grey',
      category: 'adults',
      value: 80,
      zone: 'general',
      cx: 1375.5,
      cy: 355.5
    },
    {
      id: 'A-38',
      row: 'A',
      column: 38,
      code: '8456',
      selection: true,
      color: 'red',
      category: 'adults',
      value: 60,
      zone: 'general',
      cx: 1350.9,
      cy: 374.4
    },
    {
      id: 'B-37',
      row: 'B',
      column: 37,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1453.1,
      cy: 339.9
    },
    {
      id: 'B-38',
      row: 'B',
      column: 38,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'kids',
      valuee: 50,
      zone: 'general',
      cx: 1427.7,
      cy: 359.4
    },
    {
      id: 'B-39',
      row: 'B',
      column: 39,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1400.9,
      cy: 378.8
    },
    {
      id: 'B-40',
      row: 'B',
      column: 40,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1374,
      cy: 399.5
    },
    {
      id: 'C-29',
      row: 'C',
      column: 29,
      code: '099999',
      selection: false,
      color: 'dodgerblue',
      category: 'eldery',
      value: 50,
      zone: 'general',
      cx: 1478.7,
      cy: 361.8
    },
    {
      id: 'C-30',
      row: 'C',
      column: 30,
      code: '00008',
      selection: true,
      color: 'grey',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1451.9,
      cy: 382.6
    },
    {
      id: 'C-31',
      row: 'C',
      column: 31,
      code: '050008',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1422.5,
      cy: 405.1
    },
    {
      id: 'C-32',
      row: 'C',
      column: 32,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1395.6,
      cy: 425.8
    },
    {
      id: 'D-27',
      row: 'D',
      column: 27,
      code: '059998',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1490.5,
      cy: 395.9
    },
    {
      id: 'D-28',
      row: 'D',
      column: 28,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1465.7,
      cy: 416.3
    },
    {
      id: 'D-29',
      row: 'D',
      column: 29,
      code: '05909878',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1437.9,
      cy: 435.8
    },
    {
      id: 'D-30',
      row: 'D',
      column: 30,
      code: '37260598',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1413,
      cy: 454.4
    },
    {
      id: 'E-28',
      row: 'E',
      column: 28,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'adults',
      value: 50,
      zone: 'general',
      cx: 1490.2,
      cy: 440.5
    },
    {
      id: 'E-29',
      row: 'E',
      column: 29,
      code: '0598',
      selection: false,
      color: 'dodgerblue',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1463.1,
      cy: 459.5
    },
    {
      id: 'E-30',
      row: 'E',
      column: 30,
      code: '0536398',
      selection: true,
      color: 'grey',
      category: 'kids',
      value: 50,
      zone: 'general',
      cx: 1435.8,
      cy: 479.9
    }
  ];

  const INIT_STATE = {
    seats: SEATS,
  };
  export default INIT_STATE;